import * as XLSX from 'xlsx';
import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import type { PdfInput } from './dashboardPdf';

function priorityLabel(p: string | null, ar: boolean): string {
  if (!p) return '—';
  const m: Record<string, { ar: string; en: string }> = {
    critical: { ar: 'حرجة', en: 'Critical' },
    high: { ar: 'عالية', en: 'High' },
    medium: { ar: 'متوسطة', en: 'Medium' },
    low: { ar: 'منخفضة', en: 'Low' },
  };
  return m[p] ? (ar ? m[p].ar : m[p].en) : p;
}

function statusLabel(s: string, ar: boolean): string {
  if (ar) return s === 'closed' ? 'مغلقة' : s === 'in_progress' ? 'قيد التنفيذ' : 'مفتوحة';
  return s === 'closed' ? 'Closed' : s === 'in_progress' ? 'In progress' : 'Open';
}

export async function generateDashboardExcel(input: PdfInput): Promise<string> {
  const { title, subtitle, generatedBy, rows, analytics, isArabic } = input;
  const ar = isArabic;

  const wb = XLSX.utils.book_new();
  const data: any[][] = [];

  // ── Header ──
  data.push([title]);
  data.push([subtitle]);
  data.push([`${ar ? 'أُنشئ بواسطة' : 'Generated by'}: ${generatedBy} · ${new Date().toLocaleString(ar ? 'ar-EG' : 'en-GB')}`]);
  data.push([]);

  // ── Summary ──
  data.push([ar ? 'الملخص' : 'Summary']);
  data.push([ar ? 'الإجمالي' : 'Total', ar ? 'مفتوحة' : 'Open', ar ? 'مغلقة' : 'Closed', ar ? 'الكل' : 'All']);
  data.push([analytics.total, analytics.openCount, analytics.closedCount, analytics.total]);
  data.push([]);

  // ── Priority ──
  data.push([ar ? 'التقارير حسب الأولوية' : 'Reports by Priority']);
  data.push([ar ? 'الأولوية' : 'Priority', ar ? 'العدد' : 'Count']);
  (['critical', 'high', 'medium', 'low'] as const).forEach((k) => {
    data.push([priorityLabel(k, ar), analytics.byPriority[k] || 0]);
  });
  data.push([]);

  // ── Categories ──
  data.push([ar ? 'التوزيع حسب التصنيف' : 'Distribution by Category']);
  data.push([ar ? 'التصنيف' : 'Category', ar ? 'العدد' : 'Count', ar ? 'النسبة' : 'Percentage']);
  if (analytics.topSubs.length) {
    analytics.topSubs.slice(0, 10).forEach(([k, v]) => {
      const pct = analytics.total > 0 ? ((v / analytics.total) * 100).toFixed(1) + '%' : '0.0%';
      data.push([k, v, pct]);
    });
  } else {
    data.push([ar ? 'لا بيانات' : 'No data', '', '']);
  }
  data.push([]);

  // ── Departments ──
  if (analytics.topDepts.length) {
    data.push([ar ? 'حسب القسم' : 'By Department']);
    data.push([ar ? 'القسم' : 'Department', ar ? 'العدد' : 'Count']);
    analytics.topDepts.forEach(([k, v]) => data.push([k, v]));
    data.push([]);
  }

  // ── Reports ──
  data.push([`${ar ? 'التقارير' : 'Reports'} (${rows.length})`]);
  data.push([
    '#',
    ar ? 'الوصف' : 'Description',
    ar ? 'القسم' : 'Dept',
    ar ? 'التصنيف' : 'Subcat',
    ar ? 'الأولوية' : 'Priority',
    ar ? 'الحالة' : 'Status',
    ar ? 'المُبلِّغ' : 'Reporter',
    ar ? 'التاريخ' : 'Date',
  ]);
  if (rows.length) {
    rows.forEach((r, i) => {
      data.push([
        i + 1,
        r.note,
        r.department || '—',
        r.subcategory || '—',
        priorityLabel(r.priority, ar),
        statusLabel(r.status, ar),
        r.created_by_name || '—',
        new Date(r.created_at).toLocaleDateString(ar ? 'ar-EG' : 'en-GB'),
      ]);
    });
  } else {
    data.push([ar ? 'لا توجد تقارير' : 'No reports']);
  }

  const ws = XLSX.utils.aoa_to_sheet(data);

  // Column widths
  ws['!cols'] = [
    { wch: 6 }, { wch: 45 }, { wch: 14 }, { wch: 18 },
    { wch: 12 }, { wch: 12 }, { wch: 18 }, { wch: 14 },
  ];

  XLSX.utils.book_append_sheet(wb, ws, ar ? 'التقارير' : 'Reports');

  // Real .xlsx file — documented SheetJS method for Expo
  const b64 = XLSX.write(wb, { type: 'base64', bookType: 'xlsx' });
  const filename = `dashboard-${Date.now()}.xlsx`;
  const file = new File(Paths.cache, filename);
  // فك Base64 إلى bytes وكتابتها كملف ثنائي حقيقي
  file.write(b64, { encoding: 'base64' });
  return file.uri;
}

export async function shareExcel(path: string, dialogTitle: string): Promise<void> {
  if (!(await Sharing.isAvailableAsync())) return;
  await Sharing.shareAsync(path, {
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    dialogTitle,
    UTI: 'org.openxmlformats.spreadsheetml.sheet',
  });
}
