import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  WidthType, AlignmentType, HeadingLevel, BorderStyle, ShadingType,
} from 'docx';
import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import type { PdfInput } from './dashboardPdf';

const CRIMSON = 'E5284B';
const AMBER = 'C77D2A';
const GREEN = '3E7A52';
const BLUE = '5BA9D6';
const CREAM = 'FDFAF3';
const TEXT = '2A1F22';
const TEXT_SEC = '6B5A5C';

function pLabel(p: string | null, ar: boolean): string {
  if (!p) return '—';
  const m: Record<string, { ar: string; en: string }> = {
    critical: { ar: 'حرجة', en: 'Critical' },
    high: { ar: 'عالية', en: 'High' },
    medium: { ar: 'متوسطة', en: 'Medium' },
    low: { ar: 'منخفضة', en: 'Low' },
  };
  return m[p] ? (ar ? m[p].ar : m[p].en) : p;
}

function pColor(p: string | null): string {
  const m: Record<string, string> = {
    critical: CRIMSON, high: AMBER, medium: BLUE, low: GREEN,
  };
  return p ? (m[p] || CRIMSON) : CRIMSON;
}

function sLabel(s: string, ar: boolean): string {
  if (ar) return s === 'closed' ? 'مغلقة' : s === 'in_progress' ? 'قيد التنفيذ' : 'مفتوحة';
  return s === 'closed' ? 'Closed' : s === 'in_progress' ? 'In progress' : 'Open';
}

function cell(text: string, opts: { bold?: boolean; bg?: string; color?: string; align?: any } = {}) {
  return new TableCell({
    children: [
      new Paragraph({
        alignment: opts.align,
        children: [
          new TextRun({
            text,
            bold: opts.bold,
            color: opts.color || TEXT,
            size: 20,
          }),
        ],
      }),
    ],
    shading: opts.bg
      ? { type: ShadingType.CLEAR, fill: opts.bg, color: 'auto' }
      : undefined,
  });
}

export async function generateDashboardWord(input: PdfInput): Promise<string> {
  const { title, subtitle, generatedBy, rows, analytics, isArabic } = input;
  const ar = isArabic;
  const align = ar ? AlignmentType.RIGHT : AlignmentType.LEFT;

  const sections: any[] = [];

  // ── Header ──
  sections.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      alignment: align,
      children: [new TextRun({ text: title, bold: true, color: CRIMSON, size: 40 })],
    }),
    new Paragraph({
      alignment: align,
      children: [new TextRun({ text: subtitle, color: TEXT_SEC, size: 24 })],
    }),
    new Paragraph({
      alignment: align,
      children: [new TextRun({
        text: `${ar ? 'أُنشئ بواسطة' : 'Generated by'}: ${generatedBy} · ${new Date().toLocaleString(ar ? 'ar-EG' : 'en-GB')}`,
        color: TEXT_SEC,
        size: 18,
      })],
    }),
    new Paragraph({ text: '' }),
  );

  // ── Summary ──
  sections.push(new Paragraph({
    heading: HeadingLevel.HEADING_2,
    alignment: align,
    children: [new TextRun({ text: ar ? 'الملخص' : 'Summary', bold: true, color: CRIMSON })],
  }));
  sections.push(new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          cell(String(analytics.total), { bold: true, bg: CREAM, align: AlignmentType.CENTER }),
          cell(String(analytics.openCount), { bold: true, bg: CREAM, color: AMBER, align: AlignmentType.CENTER }),
          cell(String(analytics.closedCount), { bold: true, bg: CREAM, color: GREEN, align: AlignmentType.CENTER }),
          cell(String(analytics.total), { bold: true, bg: CREAM, color: CRIMSON, align: AlignmentType.CENTER }),
        ],
      }),
      new TableRow({
        children: [
          cell(ar ? 'الإجمالي' : 'Total', { bg: CREAM, align: AlignmentType.CENTER }),
          cell(ar ? 'مفتوحة' : 'Open', { bg: CREAM, align: AlignmentType.CENTER }),
          cell(ar ? 'مغلقة' : 'Closed', { bg: CREAM, align: AlignmentType.CENTER }),
          cell(ar ? 'الكل' : 'All', { bg: CREAM, align: AlignmentType.CENTER }),
        ],
      }),
    ],
  }));
  sections.push(new Paragraph({ text: '' }));

  // ── Priority ──
  sections.push(new Paragraph({
    heading: HeadingLevel.HEADING_2,
    alignment: align,
    children: [new TextRun({ text: ar ? 'التقارير حسب الأولوية' : 'Reports by Priority', bold: true, color: CRIMSON })],
  }));
  const priorityRows = (['critical', 'high', 'medium', 'low'] as const).map((k) => {
    const v = analytics.byPriority[k] || 0;
    return new TableRow({
      children: [
        cell(pLabel(k, ar), { bold: true, bg: pColor(k), color: 'FFFFFF' }),
        cell(String(v), { bold: true, align: AlignmentType.CENTER }),
      ],
    });
  });
  sections.push(new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          cell(ar ? 'الأولوية' : 'Priority', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
          cell(ar ? 'العدد' : 'Count', { bold: true, bg: CRIMSON, color: 'FFFFFF', align: AlignmentType.CENTER }),
        ],
      }),
      ...priorityRows,
    ],
  }));
  sections.push(new Paragraph({ text: '' }));

  // ── Categories ──
  sections.push(new Paragraph({
    heading: HeadingLevel.HEADING_2,
    alignment: align,
    children: [new TextRun({ text: ar ? 'التوزيع حسب التصنيف' : 'Distribution by Category', bold: true, color: CRIMSON })],
  }));
  const catRows = analytics.topSubs.length
    ? analytics.topSubs.slice(0, 10).map(([k, v]) => {
        const pct = analytics.total > 0 ? ((v / analytics.total) * 100).toFixed(1) + '%' : '0.0%';
        return new TableRow({
          children: [
            cell(k),
            cell(String(v), { bold: true, align: AlignmentType.CENTER }),
            cell(pct, { bold: true, color: CRIMSON, align: AlignmentType.CENTER }),
          ],
        });
      })
    : [new TableRow({ children: [cell(ar ? 'لا بيانات' : 'No data', { align: AlignmentType.CENTER })] })];

  sections.push(new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          cell(ar ? 'التصنيف' : 'Category', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
          cell(ar ? 'العدد' : 'Count', { bold: true, bg: CRIMSON, color: 'FFFFFF', align: AlignmentType.CENTER }),
          cell(ar ? 'النسبة' : 'Percentage', { bold: true, bg: CRIMSON, color: 'FFFFFF', align: AlignmentType.CENTER }),
        ],
      }),
      ...catRows,
    ],
  }));
  sections.push(new Paragraph({ text: '' }));

  // ── Departments ──
  if (analytics.topDepts.length) {
    sections.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      alignment: align,
      children: [new TextRun({ text: ar ? 'حسب القسم' : 'By Department', bold: true, color: CRIMSON })],
    }));
    sections.push(new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({
          children: [
            cell(ar ? 'القسم' : 'Department', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
            cell(ar ? 'العدد' : 'Count', { bold: true, bg: CRIMSON, color: 'FFFFFF', align: AlignmentType.CENTER }),
          ],
        }),
        ...analytics.topDepts.map(([k, v]) => new TableRow({
          children: [
            cell(k),
            cell(String(v), { bold: true, align: AlignmentType.CENTER }),
          ],
        })),
      ],
    }));
    sections.push(new Paragraph({ text: '' }));
  }

  // ── Reports ──
  sections.push(new Paragraph({
    heading: HeadingLevel.HEADING_2,
    alignment: align,
    children: [new TextRun({ text: `${ar ? 'التقارير' : 'Reports'} (${rows.length})`, bold: true, color: CRIMSON })],
  }));
  const reportRows = rows.length
    ? rows.map((r, i) => new TableRow({
        children: [
          cell(String(i + 1), { align: AlignmentType.CENTER }),
          cell(r.note),
          cell(r.department || '—'),
          cell(r.subcategory || '—'),
          cell(pLabel(r.priority, ar)),
          cell(sLabel(r.status, ar)),
          cell(r.created_by_name || '—'),
          cell(new Date(r.created_at).toLocaleDateString(ar ? 'ar-EG' : 'en-GB')),
        ],
      }))
    : [new TableRow({ children: [cell(ar ? 'لا توجد تقارير' : 'No reports', { align: AlignmentType.CENTER })] })];

  sections.push(new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          cell('#', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
          cell(ar ? 'الوصف' : 'Description', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
          cell(ar ? 'القسم' : 'Dept', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
          cell(ar ? 'التصنيف' : 'Subcat', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
          cell(ar ? 'الأولوية' : 'Priority', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
          cell(ar ? 'الحالة' : 'Status', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
          cell(ar ? 'المُبلِّغ' : 'Reporter', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
          cell(ar ? 'التاريخ' : 'Date', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
        ],
      }),
      ...reportRows,
    ],
  }));

  const doc = new Document({
    sections: [{ children: sections }],
  });

  // Convert docx to base64 (Blob is not supported on React Native)
  const base64 = await Packer.toBase64String(doc);
  const filename = `dashboard-${Date.now()}.docx`;
  const file = new File(Paths.cache, filename);
  // فك Base64 إلى bytes وكتابتها كملف ثنائي حقيقي
  file.write(base64, { encoding: 'base64' });
  return file.uri;
}

export async function shareWord(path: string, dialogTitle: string): Promise<void> {
  if (!(await Sharing.isAvailableAsync())) return;
  await Sharing.shareAsync(path, {
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    dialogTitle,
    UTI: 'org.openxmlformats.wordprocessingml.document',
  });
}
