import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  WidthType, AlignmentType, HeadingLevel, ImageRun, ShadingType,
} from 'docx';
import { Buffer } from 'buffer';
import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import type { PdfInput } from './dashboardPdf';

const CRIMSON = 'E5284B';
const AMBER = 'C77D2A';
const GREEN = '3E7A52';
const BLUE = '5BA9D6';
const CREAM = 'FDFAF3';
const TEXT = '2A1F22';
const TEXT_SEC = '6B5A5C';

function pLabel(p: string | null, ar: boolean): string {
  if (!p) return '—';
  const m: Record<string, { ar: string; en: string }> = {
    critical: { ar: 'حرجة', en: 'Critical' },
    high: { ar: 'عالية', en: 'High' },
    medium: { ar: 'متوسطة', en: 'Medium' },
    low: { ar: 'منخفضة', en: 'Low' },
  };
  return m[p] ? (ar ? m[p].ar : m[p].en) : p;
}

function pColor(p: string | null): string {
  const m: Record<string, string> = { critical: CRIMSON, high: AMBER, medium: BLUE, low: GREEN };
  return p ? (m[p] || CRIMSON) : CRIMSON;
}

function sLabel(s: string, ar: boolean): string {
  if (ar) return s === 'closed' ? 'مغلقة' : s === 'in_progress' ? 'قيد التنفيذ' : 'مفتوحة';
  return s === 'closed' ? 'Closed' : s === 'in_progress' ? 'In progress' : 'Open';
}

function b64ToBytes(b64: string): Uint8Array {
  const clean = b64.replace(/^data:image\/\w+;base64,/, '');
  return new Uint8Array(Buffer.from(clean, 'base64'));
}

function cell(text: string, opts: { bold?: boolean; bg?: string; color?: string; align?: any } = {}) {
  return new TableCell({
    children: [
      new Paragraph({ bidirectional: true,
        alignment: opts.align,
        children: [new TextRun({ text, bold: opts.bold, color: opts.color || TEXT, size: 20 })],
      }),
    ],
    shading: opts.bg ? { type: ShadingType.CLEAR, fill: opts.bg, color: 'auto' } : undefined,
  });
}

export interface WordInput extends PdfInput {
  barChartBase64?: string | null;
  pieChartBase64?: string | null;
}

export async function generateDashboardWord(input: WordInput): Promise<string> {
  const { title, subtitle, generatedBy, rows, analytics, isArabic, barChartBase64, pieChartBase64 } = input;
  const ar = isArabic;
  const align = ar ? AlignmentType.RIGHT : AlignmentType.LEFT;

  const children: any[] = [];

  children.push(
    new Paragraph({ bidirectional: true,
      alignment: align,
      children: [new TextRun({ text: title, bold: true, color: CRIMSON, size: 40 })],
    }),
    new Paragraph({ bidirectional: true,
      alignment: align,
      children: [new TextRun({ text: subtitle, color: TEXT_SEC, size: 24 })],
    }),
    new Paragraph({ bidirectional: true,
      alignment: align,
      children: [new TextRun({
        text: `${ar ? 'أُنشئ بواسطة' : 'Generated by'}: ${generatedBy} · ${new Date().toLocaleString(ar ? 'ar-EG' : 'en-GB')}`,
        color: TEXT_SEC, size: 18,
      })],
    }),
    new Paragraph({ bidirectional: true, text: '' }),
  );

  // Bar chart image
  if (barChartBase64) {
    children.push(new Paragraph({ bidirectional: true,
      alignment: align,
      children: [new TextRun({ text: ar ? 'التقارير حسب الأولوية' : 'Reports by Priority', bold: true, color: CRIMSON })],
    }));
    children.push(new Paragraph({ bidirectional: true,
      alignment: AlignmentType.CENTER,
      children: [
        new ImageRun({
          type: 'png',
          data: b64ToBytes(barChartBase64),
          transformation: { width: 600, height: 350 },
        }),
      ],
    }));
    children.push(new Paragraph({ bidirectional: true, text: '' }));
  }

  // Priority table
  children.push(new Table({ visuallyRightToLeft: true,
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({ children: [
        cell(ar ? 'الأولوية' : 'Priority', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
        cell(ar ? 'العدد' : 'Count', { bold: true, bg: CRIMSON, color: 'FFFFFF', align: AlignmentType.CENTER }),
      ]}),
      ...(['critical', 'high', 'medium', 'low'] as const).map((k) => new TableRow({
        children: [
          cell(pLabel(k, ar), { bold: true, bg: pColor(k), color: 'FFFFFF' }),
          cell(String(analytics.byPriority[k] || 0), { bold: true, align: AlignmentType.CENTER }),
        ],
      })),
    ],
  }));
  children.push(new Paragraph({ bidirectional: true, text: '' }));

  // Pie chart image
  if (pieChartBase64) {
    children.push(new Paragraph({ bidirectional: true,
      alignment: align,
      children: [new TextRun({ text: ar ? 'التوزيع حسب التصنيف' : 'Distribution by Category', bold: true, color: CRIMSON })],
    }));
    children.push(new Paragraph({ bidirectional: true,
      alignment: AlignmentType.CENTER,
      children: [
        new ImageRun({
          type: 'png',
          data: b64ToBytes(pieChartBase64),
          transformation: { width: 500, height: 400 },
        }),
      ],
    }));
    children.push(new Paragraph({ bidirectional: true, text: '' }));
  }

  // Categories
  const catRows = analytics.topSubs.length
    ? analytics.topSubs.slice(0, 10).map(([k, v]) => {
        const pct = analytics.total > 0 ? ((v / analytics.total) * 100).toFixed(1) + '%' : '0.0%';
        return new TableRow({ children: [
          cell(k),
          cell(String(v), { bold: true, align: AlignmentType.CENTER }),
          cell(pct, { bold: true, color: CRIMSON, align: AlignmentType.CENTER }),
        ]});
      })
    : [new TableRow({ children: [cell(ar ? 'لا بيانات' : 'No data', { align: AlignmentType.CENTER })] })];

  children.push(new Table({ visuallyRightToLeft: true,
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({ children: [
        cell(ar ? 'التصنيف' : 'Category', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
        cell(ar ? 'العدد' : 'Count', { bold: true, bg: CRIMSON, color: 'FFFFFF', align: AlignmentType.CENTER }),
        cell(ar ? 'النسبة' : 'Percentage', { bold: true, bg: CRIMSON, color: 'FFFFFF', align: AlignmentType.CENTER }),
      ]}),
      ...catRows,
    ],
  }));
  children.push(new Paragraph({ bidirectional: true, text: '' }));

  // Reports
  children.push(new Paragraph({ bidirectional: true,
    alignment: align,
    children: [new TextRun({ text: `${ar ? 'التقارير' : 'Reports'} (${rows.length})`, bold: true, color: CRIMSON })],
  }));
  const repRows = rows.length
    ? rows.map((row, i) => new TableRow({ children: [
        cell(String(i + 1), { align: AlignmentType.CENTER }),
        cell(row.note),
        cell(row.department || '—'),
        cell(row.subcategory || '—'),
        cell(pLabel(row.priority, ar)),
        cell(sLabel(row.status, ar)),
        cell(row.created_by_name || '—'),
        cell(new Date(row.created_at).toLocaleDateString(ar ? 'ar-EG' : 'en-GB')),
      ]}))
    : [new TableRow({ children: [cell(ar ? 'لا توجد تقارير' : 'No reports', { align: AlignmentType.CENTER })] })];

  children.push(new Table({ visuallyRightToLeft: true,
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({ children: [
        cell('#', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
        cell(ar ? 'الوصف' : 'Description', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
        cell(ar ? 'القسم' : 'Dept', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
        cell(ar ? 'التصنيف' : 'Subcat', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
        cell(ar ? 'الأولوية' : 'Priority', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
        cell(ar ? 'الحالة' : 'Status', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
        cell(ar ? 'المُبلِّغ' : 'Reporter', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
        cell(ar ? 'التاريخ' : 'Date', { bold: true, bg: CRIMSON, color: 'FFFFFF' }),
      ]}),
      ...repRows,
    ],
  }));

  const doc = new Document({ sections: [{ children }] });

  const arrayBuffer = await Packer.toArrayBuffer(doc);
  const bytes = new Uint8Array(arrayBuffer);
  const filename = `dashboard-${Date.now()}.docx`;
  const file = new File(Paths.cache, filename);
  file.write(bytes);
  return file.uri;
}

export async function shareWord(path: string, dialogTitle: string): Promise<void> {
  if (!(await Sharing.isAvailableAsync())) return;
  await Sharing.shareAsync(path, {
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    dialogTitle,
  });
}
