import * as XLSX from 'xlsx-with-styles';
import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { injectImagesIntoXlsx, ImagePlacement } from './xlsxImageInjector';
import type { PdfInput } from './dashboardPdf';

export interface ExcelInput extends PdfInput {
  barChartBase64?: string | null;
  pieChartBase64?: string | null;
}

// Right-to-Left Mark — forces RTL rendering of the string
const RLM = '\u200F';

function pLabel(p: string | null, ar: boolean): string {
  if (!p) return '—';
  const m: Record<string, { ar: string; en: string }> = {
    critical: { ar: 'حرجة', en: 'Critical' },
    high: { ar: 'عالية', en: 'High' },
    medium: { ar: 'متوسطة', en: 'Medium' },
    low: { ar: 'منخفضة', en: 'Low' },
  };
  return m[p] ? (ar ? m[p].ar : m[p].en) : p;
}

function sLabel(s: string, ar: boolean): string {
  if (ar) return s === 'closed' ? 'مغلقة' : s === 'in_progress' ? 'قيد التنفيذ' : 'مفتوحة';
  return s === 'closed' ? 'Closed' : s === 'in_progress' ? 'In progress' : 'Open';
}

function b64ToBytes(b64: string): Uint8Array {
  const clean = b64.replace(/^data:image\/\w+;base64,/, '');
  const bin = atob(clean);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

// ── Cell styles ──
const BORDER = {
  top: { style: 'thin', color: { rgb: 'D9CCC2' } },
  bottom: { style: 'thin', color: { rgb: 'D9CCC2' } },
  left: { style: 'thin', color: { rgb: 'D9CCC2' } },
  right: { style: 'thin', color: { rgb: 'D9CCC2' } },
};
const RTL_ALIGN = { readingOrder: 2 as const, horizontal: 'right' as const, vertical: 'center' as const, wrapText: true as const };
const CENTER_ALIGN = { ...RTL_ALIGN, horizontal: 'center' as const };

const sTitle = () => ({ font: { bold: true, sz: 16, color: { rgb: 'B81A3A' } }, alignment: RTL_ALIGN });
const sSection = () => ({ font: { bold: true, sz: 13, color: { rgb: 'E5284B' } }, alignment: RTL_ALIGN });
const sHeader = () => ({
  font: { bold: true, sz: 11, color: { rgb: 'FFFFFF' } },
  fill: { patternType: 'solid', fgColor: { rgb: 'E5284B' } },
  alignment: CENTER_ALIGN,
  border: BORDER,
});
const sBody = () => ({ font: { sz: 11 }, alignment: RTL_ALIGN, border: BORDER });
const sNum = () => ({ font: { sz: 11, bold: true }, alignment: CENTER_ALIGN, border: BORDER });

function styleRow(ws: any, rowIdx: number, numCols: number, style: any) {
  for (let c = 0; c < numCols; c++) {
    const addr = XLSX.utils.encode_cell({ r: rowIdx, c });
    if (!ws[addr]) continue;
    ws[addr].s = style;
  }
}

export async function generateDashboardExcel(input: ExcelInput): Promise<string> {
  const { title, subtitle, generatedBy, rows, analytics, isArabic, barChartBase64, pieChartBase64 } = input;
  const ar = isArabic;
  const R = (s: string) => (ar ? RLM + s : s);

  const aoa: any[][] = [];

  // Header
  aoa.push([R(title)]);
  aoa.push([R(subtitle)]);
  aoa.push([R(`${ar ? 'أُنشئ بواسطة' : 'Generated by'}: ${generatedBy} · ${new Date().toLocaleString('en-GB')}`)]);
  aoa.push([]);

  // Summary
  const sumTitle = aoa.length;
  aoa.push([R(ar ? 'الملخص' : 'Summary')]);
  const sumHeader = aoa.length;
  aoa.push([R(ar ? 'الإجمالي' : 'Total'), R(ar ? 'مفتوحة' : 'Open'), R(ar ? 'مغلقة' : 'Closed'), R(ar ? 'الكل' : 'All')]);
  const sumData = aoa.length;
  aoa.push([analytics.total, analytics.openCount, analytics.closedCount, analytics.total]);
  aoa.push([]);
  aoa.push([]);

  // Bar chart anchor
  const barAnchorRow = aoa.length;
  for (let i = 0; i < 22; i++) aoa.push([]);

  // Priority table
  const priTitle = aoa.length;
  aoa.push([R(ar ? 'التقارير حسب الأولوية' : 'Reports by Priority')]);
  const priHeader = aoa.length;
  aoa.push([R(ar ? 'الأولوية' : 'Priority'), R(ar ? 'العدد' : 'Count')]);
  const priStart = aoa.length;
  (['critical', 'high', 'medium', 'low'] as const).forEach((k) => {
    aoa.push([R(pLabel(k, ar)), analytics.byPriority[k] || 0]);
  });
  const priEnd = aoa.length - 1;
  aoa.push([]);

  // Pie chart anchor
  const pieAnchorRow = aoa.length;
  for (let i = 0; i < 25; i++) aoa.push([]);

  // Categories
  const catTitle = aoa.length;
  aoa.push([R(ar ? 'التوزيع حسب التصنيف' : 'Distribution by Category')]);
  const catHeader = aoa.length;
  aoa.push([R(ar ? 'التصنيف' : 'Category'), R(ar ? 'العدد' : 'Count'), R(ar ? 'النسبة' : 'Percentage')]);
  const catStart = aoa.length;
  if (analytics.topSubs.length) {
    analytics.topSubs.slice(0, 10).forEach(([k, v]) => {
      const pct = analytics.total > 0 ? ((v / analytics.total) * 100).toFixed(1) + '%' : '0.0%';
      aoa.push([R(k), v, pct]);
    });
  }
  const catEnd = aoa.length - 1;
  aoa.push([]);

  // Reports
  const repTitle = aoa.length;
  aoa.push([R(`${ar ? 'التقارير' : 'Reports'} (${rows.length})`)]);
  const repHeader = aoa.length;
  aoa.push([
    '#',
    R(ar ? 'الوصف' : 'Description'),
    R(ar ? 'القسم' : 'Dept'),
    R(ar ? 'التصنيف' : 'Subcat'),
    R(ar ? 'الأولوية' : 'Priority'),
    R(ar ? 'الحالة' : 'Status'),
    R(ar ? 'المُبلِّغ' : 'Reporter'),
    R(ar ? 'التاريخ' : 'Date'),
  ]);
  const repStart = aoa.length;
  rows.forEach((row, i) => {
    aoa.push([
      i + 1,
      R(row.note),
      R(row.department || '—'),
      R(row.subcategory || '—'),
      R(pLabel(row.priority, ar)),
      R(sLabel(row.status, ar)),
      R(row.created_by_name || '—'),
      new Date(row.created_at).toLocaleDateString('en-GB'),
    ]);
  });
  const repEnd = aoa.length - 1;

  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws['!cols'] = [
    { wch: 6 }, { wch: 46 }, { wch: 16 }, { wch: 20 },
    { wch: 14 }, { wch: 14 }, { wch: 20 }, { wch: 12 },
    { wch: 10 }, { wch: 10 }, { wch: 10 },
  ];

  // Apply styles
  styleRow(ws, 0, 1, sTitle());
  styleRow(ws, 1, 1, { alignment: RTL_ALIGN });
  styleRow(ws, 2, 1, { alignment: RTL_ALIGN, font: { sz: 10, color: { rgb: '6B5A5C' } } });

  styleRow(ws, sumTitle, 1, sSection());
  styleRow(ws, sumHeader, 4, sHeader());
  styleRow(ws, sumData, 4, sNum());

  styleRow(ws, priTitle, 1, sSection());
  styleRow(ws, priHeader, 2, sHeader());
  for (let r = priStart; r <= priEnd; r++) styleRow(ws, r, 2, sBody());

  styleRow(ws, catTitle, 1, sSection());
  styleRow(ws, catHeader, 3, sHeader());
  if (catEnd >= catStart) for (let r = catStart; r <= catEnd; r++) styleRow(ws, r, 3, sBody());

  styleRow(ws, repTitle, 1, sSection());
  styleRow(ws, repHeader, 8, sHeader());
  if (repEnd >= repStart) for (let r = repStart; r <= repEnd; r++) styleRow(ws, r, 8, sBody());

  // Embed images — both bar and pie

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, ar ? 'التقارير' : 'Reports');

  const buf = XLSX.write(wb, { type: 'array', bookType: 'xlsx' });
  let bytes = new Uint8Array(buf);

  const imageList: ImagePlacement[] = [];
  if (barChartBase64) {
    imageList.push({ base64: barChartBase64, col: 0, row: barAnchorRow, widthPx: 620 });
  }
  if (pieChartBase64) {
    imageList.push({ base64: pieChartBase64, col: 0, row: pieAnchorRow, widthPx: 620 });
  }
  bytes = injectImagesIntoXlsx(bytes, imageList);

  const filename = `dashboard-${Date.now()}.xlsx`;
  const file = new File(Paths.cache, filename);
  file.write(bytes);
  return file.uri;
}

export async function shareExcel(path: string, dialogTitle: string): Promise<void> {
  if (!(await Sharing.isAvailableAsync())) return;
  await Sharing.shareAsync(path, {
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    dialogTitle,
  });
}
